import React, { useState, useEffect } from 'react';
import { SettingsModal } from './components/SettingsModal.jsx';
import { FaUser, FaCloudUploadAlt, FaChevronDown, FaFile, FaTimes } from 'react-icons/fa';
import { FiMinimize2 } from "react-icons/fi";
import { MdCancel } from "react-icons/md";
import { RxDividerVertical } from "react-icons/rx";
import { MODELS } from './utils/constants';

export const App = () => {
  const [showSettings, setShowSettings] = useState(false);
  const [selectedModel, setSelectedModel] = useState(MODELS.free[0].id);
  const [prompt, setPrompt] = useState('');
  const [isDragOver, setIsDragOver] = useState(false);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [selectedFile, setSelectedFile] = useState(null);
  const [processingStatus, setProcessingStatus] = useState('idle'); // 'idle' | 'executing' | 'completed'
  const [terminalLogs, setTerminalLogs] = useState([]);
  const [outputFile, setOutputFile] = useState(null);
  const [showApiKeyError, setShowApiKeyError] = useState(false);
  const [promptError, setPromptError] = useState(false);
  const [executionError, setExecutionError] = useState(null);
  const terminalRef = React.useRef(null);

  useEffect(() => {
    const savedModel = localStorage.getItem('groq_model');
    if (savedModel) setSelectedModel(savedModel);
  }, []);

  // Auto-scroll terminal when new logs arrive
  useEffect(() => {
    if (terminalRef.current && processingStatus === 'executing') {
      terminalRef.current.scrollTop = terminalRef.current.scrollHeight;
    }
  }, [terminalLogs, processingStatus]);

  const handleModelChange = (modelId) => {
    setSelectedModel(modelId);
    localStorage.setItem('groq_model', modelId);
  };

  const handleDragOver = (e) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = (e) => {
    e.preventDefault();
    setIsDragOver(false);
  };

  const handleDrop = (e) => {
    e.preventDefault();
    setIsDragOver(false);

    const files = Array.from(e.dataTransfer.files);
    if (files.length > 0) {
      const file = files[0];
      window.electronAPI.log('File dropped in app.jsx:', file.name, 'path property:', file.path);
      try {
        const filePath = window.electronAPI.getFilePath(file);
        console.log('File dropped:', file.name);
        console.log('File path:', filePath);
        window.electronAPI.log('Final filePath:', filePath);

        setSelectedFile({
          name: file.name,
          path: filePath,
          extension: file.name.split('.').pop().toUpperCase()
        });

      } catch (e) {
        window.electronAPI.log('Error calling getFilePath:', e.toString());
      }
    }
  };

  const handleExecution = async () => {
    if (!selectedFile || !prompt.trim()) return;

    // Check if API key is set
    const apiKeyCheck = await window.electronAPI.getApiKey();
    if (!apiKeyCheck.ok || !apiKeyCheck.apiKey) {
      setShowApiKeyError(true);
      setPromptError(true);
      setTimeout(() => setPromptError(false), 2000);
      setTimeout(() => setShowApiKeyError(false), 3000);
      return;
    }

    setProcessingStatus('executing');
    setTerminalLogs([]);

    // Subscribe to logs
    window.electronAPI.onFFmpegLog((msg) => {
      setTerminalLogs(prev => [...prev, msg]);
    });

    try {
      window.electronAPI.log("Sending prompt to Groq:", prompt);
      const genResult = await window.electronAPI.groqGenerate({
        prompt,
        model: selectedModel,
        file: selectedFile.path
      });

      if (!genResult.ok) {
        setExecutionError(genResult.error || 'Failed to generate FFmpeg command');
        setProcessingStatus('idle');
        setTimeout(() => setExecutionError(null), 5000);
        return;
      }

      const { exe, args } = genResult.data;
      const outputFilename = genResult.outputFilename;

      window.electronAPI.log("Executing FFmpeg:", exe, args);
      const execResult = await window.electronAPI.executeFFmpeg(exe, args);

      if (execResult.ok) {
        setProcessingStatus('completed');

        // Determine extension from the output filename generated by backend
        // Note: backend generates generic name without extension in 'filename' variable usually, 
        // but the 'args' will contain the actual output file path with extension.
        // Let's rely on the args to find the output path, or the user prompt context.
        // Actually, groqClient.js appends nothing to filename, the LLM decides the extension based on placeholder.
        // The 'outputFilename' variable acts as a base.
        // To cover all bases, let's look at the last arg which is usually the output file.
        const actualOutputPath = args[args.length - 1];
        const ext = actualOutputPath.split('.').pop().toUpperCase();
        const name = actualOutputPath.split(/[/\\]/).pop();

        setOutputFile({
          name: name,
          path: actualOutputPath,
          extension: ext
        });
      } else {
        setExecutionError(execResult.error || 'FFmpeg execution failed');
        setProcessingStatus('idle');
        setTimeout(() => setExecutionError(null), 5000);
      }

    } catch (e) {
      setExecutionError(e.message || 'An unexpected error occurred');
      setProcessingStatus('idle');
      setTimeout(() => setExecutionError(null), 5000);
    } finally {
      window.electronAPI.offFFmpegLog();
    }
  };

  const fileInputRef = React.useRef(null);

  const handleFileSelect = (e) => {
    const files = Array.from(e.target.files);
    if (files.length > 0) {
      const file = files[0];
      window.electronAPI.log('File selected via click:', file.name);
      try {
        const filePath = window.electronAPI.getFilePath(file);
        console.log('File selected:', file.name);
        console.log('File path:', filePath);
        window.electronAPI.log('Final filePath:', filePath);

        setSelectedFile({
          name: file.name,
          path: filePath,
          extension: file.name.split('.').pop().toUpperCase()
        });

      } catch (e) {
        window.electronAPI.log('Error calling getFilePath:', e.toString());
      }
    }
  };

  const handleRemoveFile = (e) => {
    e.stopPropagation(); // Prevent click from triggering input
    setSelectedFile(null);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    // Outer Wrapper - defines the window shape and holds the border logic
    <div className="relative h-screen w-screen rounded-[12px] overflow-hidden bg-transparent">

      {/* Hidden File Input */}
      <input
        type="file"
        ref={fileInputRef}
        onChange={handleFileSelect}
        className="hidden"
        style={{ display: 'none' }}
      />

      {/* Corner Glows */}
      {/* Top Left - Pinkish */}
      <div className="absolute top-0 left-0 w-60 h-60 bg-pink-400  blur-[40px] pointer-events-none rounded-full translate-x-[-30%] translate-y-[-30%]" />
      {/* Top Right - White (default) */}
      <div className="absolute top-0 right-0 w-40 h-40 bg-white opacity-40 blur-[50px] pointer-events-none rounded-full translate-x-[30%] translate-y-[-30%]" />
      {/* Bottom Left - White (default) */}
      <div className="absolute bottom-0 left-0 w-40 h-40 bg-white opacity-40 blur-[50px] pointer-events-none rounded-full translate-x-[-30%] translate-y-[30%]" />
      {/* Bottom Right - Neonish (Cyan/Blue) */}
      <div className="absolute bottom-0 right-0 w-60 h-60 bg-cyan-400  blur-[40px] pointer-events-none rounded-full translate-x-[30%] translate-y-[30%]" />

      {/* Inner Content - The actual app UI */}
      <div
        className="absolute inset-[2px] rounded-[11px] bg-[rgba(0,0,0,0.82)] backdrop-blur-3xl flex flex-col overflow-hidden group"
        onMouseMove={(e) => {
          const rect = e.currentTarget.getBoundingClientRect();
          const x = e.clientX - rect.left;
          const y = e.clientY - rect.top;
          e.currentTarget.style.setProperty('--mouse-x', `${x}px`);
          e.currentTarget.style.setProperty('--mouse-y', `${y}px`);
        }}
        style={{
          // Preserving user's grid settings
          color: 'white',
          backgroundImage: `
            linear-gradient(to right, rgba(255, 255, 255, 0.2) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(255, 255, 255, 0.2) 1px, transparent 1px)
          `,
          backgroundSize: '40px 40px'
        }}
      >
        {/* Grid Highlight Overlay */}
        <div
          className="absolute inset-0 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-300"
          style={{
            backgroundImage: `
              linear-gradient(to right, rgba(255, 255, 255, 0.5) 1px, transparent 1px),
              linear-gradient(to bottom, rgba(255, 255, 255, 0.5) 1px, transparent 1px)
            `,
            backgroundSize: '40px 40px',
            maskImage: `radial-gradient(200px circle at var(--mouse-x) var(--mouse-y), black, transparent)`,
            WebkitMaskImage: `radial-gradient(200px circle at var(--mouse-x) var(--mouse-y), black, transparent)`,
          }}
        />
        {/* Custom Title Bar / Drag Region */}
        <div style={{
          height: '60px',
          WebkitAppRegion: 'drag', // Electron specific: allows dragging
          display: 'flex',
          alignItems: 'center',
          paddingLeft: '10px',
          cursor: 'default',
          paddingRight: '10px',
          justifyContent: "flex-end",
          position: 'relative',
          // border: '1px solid rgba(255,255,255,0.2)',
        }}>

          <span className="absolute w-full h-full top-0 left-0 flex items-center justify-center">
            <span className="text-white rounded-full backdrop-blur-2xl bg-[rgba(255,255,255,0.3)] text-xl px-3 py-1">FFmpeg Copilot</span>
          </span>



          <div
            style={{
              WebkitAppRegion: 'no-drag',
              display: 'flex',
              alignItems: 'center',
              gap: '0px',
              background: 'rgba(0,0,0,0.5)',
              backdropFilter: 'blur(16px)',
              borderRadius: '14px',
              padding: '5px',
              border: '1px solid rgba(255,255,255,0.1)',
              boxShadow: '0 4px 20px rgba(236,72,153,0.25), 0 0 40px rgba(236,72,153,0.15), inset 0 1px 0 rgba(255,255,255,0.08)'
            }}
            className="animate-shadow-pulse "
          >
            {/* Account Button */}
            <button
              onClick={() => setShowSettings(true)}
              title="Account Settings"
              style={{
                background: 'transparent',
                border: 'none',
                cursor: 'pointer',
                padding: '7px 11px',
                borderRadius: '10px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                transition: 'all 0.2s',
                color: 'rgb(163, 163, 163)'
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = 'rgba(255,255,255,0.1)';
                e.currentTarget.style.color = 'white';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = 'transparent';
                e.currentTarget.style.color = 'rgb(163, 163, 163)';
              }}
            >
              <FaUser size={13} />
            </button>

            {/* Divider */}
            <RxDividerVertical size={20} style={{ color: 'rgba(255,255,255,0.4)', margin: '0 -2px' }} />


            {/* Minimize Button */}
            <button
              onClick={() => window.electronAPI.minimizeWindow()}
              title="Minimize"
              style={{
                background: 'transparent',
                border: 'none',
                cursor: 'pointer',
                padding: '7px 11px',
                borderRadius: '10px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                transition: 'all 0.2s',
                color: 'rgb(163, 163, 163)'
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = 'rgba(255,255,255,0.1)';
                e.currentTarget.style.color = 'white';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = 'transparent';
                e.currentTarget.style.color = 'rgb(163, 163, 163)';
              }}
            >
              <FiMinimize2 size={14} />
            </button>

            {/* Divider */}
            <RxDividerVertical size={20} style={{ color: 'rgba(255,255,255,0.4)', margin: '0 -2px' }} />


            {/* Close Button */}
            <button
              onClick={() => window.electronAPI.closeWindow()}
              title="Close"
              style={{
                background: 'transparent',
                border: 'none',
                cursor: 'pointer',
                padding: '7px 11px',
                borderRadius: '10px',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                transition: 'all 0.2s',
                color: 'rgb(236, 112, 153)'
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = 'rgba(239,68,68,0.2)';
                e.currentTarget.style.color = '#ef4444';
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = 'transparent';
                e.currentTarget.style.color = 'rgb(236, 112, 153)';
              }}
            >
              <MdCancel size={16} />
            </button>
          </div>
        </div>


        {/* Main Content Area */}
        <div className="flex-1 flex flex-col items-center justify-center  w-full max-w-3xl mx-auto z-10" style={{ WebkitAppRegion: 'no-drag' }}>

          {/* Header Text */}
          <h1 className="text-5xl text-white select-none font-amsterdam">
            FFmpeg, <span className="font-polea">but Sexy</span>!
          </h1>

          {/* Spacer to force gap */}
          <div className="h-16 w-full"></div>

          {/* File Drop Zone with Rotating Glow */}
          {/* File Drop Zone / Terminal / Result */}
          <div className="relative group w-[80%] h-52 transition-all duration-300">
            {/* Rotating Glow Shadow */}
            <div
              className={`absolute -inset-0.5 rounded-3xl opacity-75 blur-xl transition duration-1000 group-hover:opacity-100 group-hover:duration-200 ${processingStatus === 'executing' ? 'animate-agent-flash' : 'animate-gradient-border'}`}
              style={{
                background: `conic-gradient(from var(--gradient-angle), #ff4545, #00ff99, #006aff, #ff0095, #ff4545)`
              }}
            ></div>

            {/* Rotating Border */}
            <div
              className={`absolute -inset-0.5 rounded-3xl ${processingStatus === 'executing' ? 'animate-agent-flash' : 'animate-gradient-border'}`}
              style={{
                background: `conic-gradient(from var(--gradient-angle), #ff4545, #00ff99, #006aff, #ff0095, #ff4545)`
              }}
            ></div>

            {/* Actual Drop Zone Content - Black Background */}
            <div
              className={`relative h-full w-full rounded-3xl flex flex-col items-center justify-center transition-all duration-300 backdrop-blur-md z-10 overflow-hidden ${processingStatus === 'executing'
                ? 'bg-black shadow-agent-inner'
                : isDragOver
                  ? 'bg-black scale-[0.99] border hover:border-[rgba(255,255,255,0.1)] cursor-pointer'
                  : 'bg-black border border-[rgba(255,255,255,0.1)] cursor-pointer'
                }`}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              onClick={() => processingStatus === 'idle' && !selectedFile && fileInputRef.current.click()}
            >
              {processingStatus === 'executing' ? (
                // Terminal View
                <div
                  ref={terminalRef}
                  className="w-full h-full p-4 font-mono text-xs text-green-400 overflow-y-auto flex flex-col items-start justify-start text-left [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-track]:bg-transparent [&::-webkit-scrollbar-thumb]:bg-neutral-800 [&::-webkit-scrollbar-thumb]:rounded-full"
                  style={{ WebkitAppRegion: 'no-drag' }}
                >
                  {terminalLogs.map((log, index) => (
                    <div key={index} className="whitespace-pre-wrap mb-1 w-full break-all opacity-0 animate-slide-up" style={{ animationDelay: `${index * 50}ms`, animationFillMode: 'forwards' }}>
                      <span className="text-gray-500 mr-2 select-none">$</span>
                      {log}
                    </div>
                  ))}
                </div>
              ) : processingStatus === 'completed' && outputFile ? (
                // Result View
                <div
                  className="flex flex-col items-center justify-center relative w-full h-full animate-zoom-in cursor-pointer hover:bg-[rgba(255,255,255,0.02)] transition-colors"
                  onClick={() => window.electronAPI.showInFolder(outputFile.path)}
                  title="Click to open folder"
                >
                  <button
                    onClick={(e) => { e.stopPropagation(); setProcessingStatus('idle'); setOutputFile(null); }}
                    className="absolute top-2 right-2 p-1.5 rounded-full bg-[rgba(255,255,255,0.1)] hover:bg-[rgba(255,255,255,0.2)] text-neutral-400 hover:text-white transition-colors z-20"
                    title="Reset"
                  >
                    <FaTimes size={12} />
                  </button>

                  <div className="relative mb-3">
                    <FaFile size={48} className="text-cyan-500 drop-shadow-[0_0_15px_rgba(34,211,238,0.5)]" />
                    <span className="absolute inset-0 flex items-center justify-center text-[10px] font-bold text-black pt-1.5 select-none">
                      {outputFile.extension}
                    </span>
                  </div>

                  <p className="text-white font-medium text-sm max-w-[90%] truncate px-4" title={outputFile.name}>
                    {outputFile.name}
                  </p>
                  <p className="text-neutral-500 text-xs mt-1 max-w-[80%] truncate">
                    Saved at: {outputFile.path}
                  </p>
                  <div className="mt-4 flex items-center gap-2 text-green-400 text-[10px] font-mono px-3 py-1 rounded-full bg-[rgba(74,222,128,0.1)] border border-[rgba(74,222,128,0.2)]">
                    <span className="w-1.5 h-1.5 rounded-full bg-green-400 animate-pulse" />
                    Process Completed Successfully
                  </div>
                </div>
              ) : selectedFile ? (
                <div className="flex flex-col items-center justify-center relative w-full h-full animate-zoom-in">
                  {/* Cancel Button */}
                  <button
                    onClick={handleRemoveFile}
                    className="absolute top-2 right-2 p-1.5 rounded-full bg-[rgba(255,255,255,0.1)] hover:bg-[rgba(255,255,255,0.2)] text-neutral-400 hover:text-red-400 transition-colors z-20"
                    title="Remove file"
                  >
                    <FaTimes size={12} />
                  </button>

                  {/* File Icon with Extension */}
                  <div className="relative mb-3">
                    <FaFile size={48} className="text-neutral-600" />
                    <span className="absolute inset-0 flex items-center justify-center text-[10px] font-bold text-black pt-1.5 select-none">
                      {selectedFile.extension.slice(0, 4)}
                    </span>
                  </div>

                  <p className="text-white font-medium text-sm max-w-[90%] truncate px-4" title={selectedFile.name}>
                    {selectedFile.name}
                  </p>
                  <p className="text-neutral-500 text-xs mt-1">Ready to process</p>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center">
                  <div className={`p-4 rounded-full mb-3 transition-colors ${isDragOver ? 'bg-[rgba(34,211,238,0.2)]' : 'bg-[rgba(255,255,255,0.05)]'}`}>
                    <FaCloudUploadAlt size={24} className={isDragOver ? 'text-cyan-400' : 'text-neutral-400'} />
                  </div>
                  <p className="text-neutral-300 font-medium">Drop image, video or audio files</p>
                  <p className="text-neutral-500 text-xs mt-1">Supports MP4, AVI, MP3, WAV, JPG, PNG</p>
                </div>
              )}
            </div>
          </div>

          {/* Spacer to force gap */}
          <div className="h-14 w-full"></div>
          {/* Prompt Input Area - Simplified & Polished */}
          <div
            className={`relative w-[90%] max-w-2xl bg-[rgba(0,0,0,0.3)] backdrop-blur-md border rounded-3xl shadow-lg transition-all duration-300 overflow-visible ${promptError
              ? 'border-red-500 animate-pulse-border'
              : 'border-[rgba(255,255,255,0.1)] hover:border-[rgba(255,255,255,0.2)]'
              }`}
            style={{ WebkitAppRegion: 'no-drag' }}
          >
            {/* Padded wrapper */}
            <div style={{ padding: '20px', paddingBottom: '40px' }}>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    if (prompt.trim()) {
                      console.log("Send prompt:", prompt);
                      handleExecution();
                      setPrompt('');
                    }
                  }
                }}
                placeholder="Ask anything..."
                style={{
                  width: '100%',
                  height: '88px',
                  background: 'transparent',
                  border: 'none',
                  outline: 'none',
                  color: 'white',
                  fontSize: '18px',
                  lineHeight: '1.5',
                  resize: 'none',
                  padding: '0',
                  margin: '0',
                  boxSizing: 'border-box'
                }}
                className='[&::-webkit-scrollbar]:w-2
  [&::-webkit-scrollbar-track]:rounded-full
  [&::-webkit-scrollbar-track]:bg-gray-100
  [&::-webkit-scrollbar-thumb]:rounded-full
  [&::-webkit-scrollbar-thumb]:bg-gray-300
  dark:[&::-webkit-scrollbar-track]:bg-neutral-700
  dark:[&::-webkit-scrollbar-thumb]:bg-neutral-500'
              />
            </div>

            {/* Model Selector - Absolute Positioned */}
            <div className="absolute bottom-4 right-4 z-50">
              <div className="relative">
                <button
                  onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '8px',
                    fontSize: '12px',
                    fontWeight: '500',
                    color: isDropdownOpen ? 'white' : 'rgb(163, 163, 163)',
                    background: 'rgba(0,0,0,0.6)',
                    backdropFilter: 'blur(12px)',
                    border: `1px solid ${isDropdownOpen ? 'rgba(34,211,238,0.5)' : 'rgba(255,255,255,0.15)'}`,
                    padding: '8px 14px',
                    borderRadius: '10px',
                    cursor: 'pointer',
                    transition: 'all 0.2s',
                    boxShadow: isDropdownOpen ? '0 0 20px rgba(34,211,238,0.3)' : 'none',
                    userSelect: 'none'
                  }}
                  onMouseEnter={(e) => {
                    if (!isDropdownOpen) {
                      e.currentTarget.style.borderColor = 'rgba(255,255,255,0.25)';
                      e.currentTarget.style.color = 'white';
                    }
                  }}
                  onMouseLeave={(e) => {
                    if (!isDropdownOpen) {
                      e.currentTarget.style.borderColor = 'rgba(255,255,255,0.15)';
                      e.currentTarget.style.color = 'rgb(163, 163, 163)';
                    }
                  }}
                >
                  <span style={{
                    width: '6px',
                    height: '6px',
                    borderRadius: '50%',
                    background: '#22d3ee',
                    boxShadow: '0 0 8px #22d3ee',
                    display: 'block'
                  }}></span>
                  <span style={{ fontSize: '12px', fontWeight: '500' }}>
                    {(() => {
                      const allModels = [...MODELS.free, ...MODELS.paid];
                      const current = allModels.find(m => m.id === selectedModel);
                      return current ? current.name.replace(/ \(.*\)/, '') : selectedModel;
                    })()}
                  </span>
                  <FaChevronDown
                    size={10}
                    style={{
                      marginLeft: '4px',
                      transition: 'transform 0.2s',
                      transform: isDropdownOpen ? 'rotate(180deg)' : 'rotate(0deg)'
                    }}
                  />
                </button>

                {/* Dropdown Menu - Opens Upwards */}
                {isDropdownOpen && (
                  <div
                    className="absolute animate-in fade-in zoom-in-95 duration-200"
                    style={{
                      bottom: 'calc(100% + 8px)',
                      right: 0,
                      width: '280px',
                      maxHeight: '280px',
                      borderRadius: '14px',
                      overflow: 'hidden',
                      transformOrigin: 'bottom right'
                    }}
                  >
                    {/* Gradient Border Effect */}
                    <div style={{
                      position: 'absolute',
                      inset: '-1px',
                      background: 'linear-gradient(135deg, rgba(34,211,238,0.5), rgba(59,130,246,0.5))',
                      borderRadius: '14px',
                      zIndex: -1
                    }} />

                    <div style={{
                      position: 'relative',
                      background: 'rgba(10,10,10,0.95)',
                      backdropFilter: 'blur(20px)',
                      borderRadius: '14px',
                      border: '1px solid rgba(255,255,255,0.1)',
                      boxShadow: '0 20px 40px rgba(0,0,0,0.5)',
                      overflow: 'hidden'
                    }}>
                      {/* Header */}
                      <div style={{
                        padding: '12px 14px',
                        borderBottom: '1px solid rgba(255,255,255,0.1)',
                        background: 'rgba(255,255,255,0.02)',
                        userSelect: 'none'
                      }}>
                        <div style={{ fontSize: '11px', fontWeight: '600', color: 'rgb(163, 163, 163)', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                          Select Model
                        </div>
                      </div>

                      {/* Models List */}
                      <div style={{
                        maxHeight: '220px',
                        overflowY: 'auto',
                        padding: '6px'
                      }}
                        className="[&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-track]:bg-transparent [&::-webkit-scrollbar-thumb]:bg-neutral-700 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb:hover]:bg-neutral-600"
                      >
                        {[...MODELS.free, ...MODELS.paid].map((model) => {
                          const isSelected = selectedModel === model.id;
                          return (
                            <button
                              key={model.id}
                              onClick={() => {
                                handleModelChange(model.id);
                                setIsDropdownOpen(false);
                              }}
                              style={{
                                width: '100%',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '10px',
                                padding: '10px 12px',
                                borderRadius: '8px',
                                background: isSelected ? 'rgba(34,211,238,0.15)' : 'transparent',
                                border: 'none',
                                cursor: 'pointer',
                                transition: 'all 0.15s',
                                marginBottom: '2px',
                                userSelect: 'none'
                              }}
                              onMouseEnter={(e) => {
                                if (!isSelected) {
                                  e.currentTarget.style.background = 'rgba(255,255,255,0.08)';
                                }
                              }}
                              onMouseLeave={(e) => {
                                if (!isSelected) {
                                  e.currentTarget.style.background = 'transparent';
                                }
                              }}
                            >
                              <div style={{
                                width: '18px',
                                height: '18px',
                                borderRadius: '50%',
                                border: `2px solid ${isSelected ? '#22d3ee' : 'rgb(115, 115, 115)'}`,
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                flexShrink: 0,
                                transition: 'all 0.15s'
                              }}>
                                {isSelected && (
                                  <div style={{
                                    width: '8px',
                                    height: '8px',
                                    borderRadius: '50%',
                                    background: '#22d3ee',
                                    boxShadow: '0 0 6px #22d3ee'
                                  }} />
                                )}
                              </div>
                              <span style={{
                                fontSize: '13px',
                                fontWeight: '500',
                                color: isSelected ? '#22d3ee' : 'rgb(212, 212, 212)',
                                textAlign: 'left',
                                flex: 1
                              }}>
                                {model.name}
                              </span>
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Enter hint - Absolute Positioned */}
            <div className="absolute bottom-5 left-4 text-[10px] text-neutral-500 font-medium select-none pointer-events-none">
              Press <span className="text-neutral-400">Enter</span> to send
            </div>
          </div>

        </div>

        {/* API Key Error Notification */}
        {showApiKeyError && (
          <div
            className="fixed top-20 left-1/2 transform -translate-x-1/2 z-[150] animate-in slide-in-from-top-4 fade-in duration-300"
            style={{ width: '420px' }}
          >
            <div className="relative">
              {/* Glow Effect */}
              <div
                className="absolute -inset-0.5 rounded-2xl opacity-75 blur-lg"
                style={{ background: 'linear-gradient(135deg, #ef4444, #dc2626)' }}
              />

              {/* Notification Content */}
              <div className="relative bg-black rounded-2xl border border-red-500 shadow-2xl overflow-hidden">
                {/* Header with Icon and Close Button */}
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', padding: '20px 20px 0 20px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{
                      width: '48px',
                      height: '48px',
                      borderRadius: '50%',
                      background: 'rgba(239, 68, 68, 0.15)',
                      border: '2px solid rgba(239, 68, 68, 0.3)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      flexShrink: 0
                    }}>
                      <span style={{ color: '#ef4444', fontSize: '24px', fontWeight: 'bold' }}>!</span>
                    </div>
                    <div>
                      <h3 style={{ color: 'white', fontWeight: '600', fontSize: '18px', marginBottom: '4px', marginTop: 0 }}>
                        API Key Required
                      </h3>
                      <p style={{ color: 'rgb(212, 212, 212)', fontSize: '13px', lineHeight: '1.5', margin: 0 }}>
                        Please configure your API key
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => setShowApiKeyError(false)}
                    style={{
                      background: 'transparent',
                      border: 'none',
                      color: 'rgb(163, 163, 163)',
                      cursor: 'pointer',
                      padding: '4px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      transition: 'color 0.2s',
                      flexShrink: 0
                    }}
                    onMouseEnter={(e) => e.target.style.color = 'white'}
                    onMouseLeave={(e) => e.target.style.color = 'rgb(163, 163, 163)'}
                  >
                    <FaTimes size={16} />
                  </button>
                </div>

                {/* Message */}
                <div style={{ padding: '16px 20px' }}>
                  <p style={{ color: 'rgb(163, 163, 163)', fontSize: '14px', lineHeight: '1.6', margin: 0 }}>
                    Set your Groq API key in settings to start executing FFmpeg commands.
                  </p>
                </div>

                {/* Action Button */}
                <div style={{ padding: '0 20px 20px 20px' }}>
                  <button
                    onClick={() => {
                      setShowApiKeyError(false);
                      setShowSettings(true);
                    }}
                    style={{
                      width: '100%',
                      padding: '12px 16px',
                      background: '#ef4444',
                      border: 'none',
                      borderRadius: '10px',
                      color: 'white',
                      fontSize: '14px',
                      fontWeight: '500',
                      cursor: 'pointer',
                      transition: 'all 0.2s'
                    }}
                    onMouseEnter={(e) => {
                      e.target.style.background = '#dc2626';
                      e.target.style.transform = 'scale(1.02)';
                    }}
                    onMouseLeave={(e) => {
                      e.target.style.background = '#ef4444';
                      e.target.style.transform = 'scale(1)';
                    }}
                  >
                    Open Settings
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Execution Error Notification */}
        {executionError && (
          <div
            className="fixed top-20 left-1/2 transform -translate-x-1/2 z-[150] animate-in slide-in-from-top-4 fade-in duration-300"
            style={{ width: '420px' }}
          >
            <div className="relative">
              {/* Glow Effect */}
              <div
                className="absolute -inset-0.5 rounded-2xl opacity-75 blur-lg"
                style={{ background: 'linear-gradient(135deg, #f59e0b, #d97706)' }}
              />

              {/* Notification Content */}
              <div className="relative bg-black rounded-2xl border border-orange-500 shadow-2xl overflow-hidden">
                {/* Header with Icon and Close Button */}
                <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', padding: '20px 20px 0 20px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{
                      width: '48px',
                      height: '48px',
                      borderRadius: '50%',
                      background: 'rgba(245, 158, 11, 0.15)',
                      border: '2px solid rgba(245, 158, 11, 0.3)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      flexShrink: 0
                    }}>
                      <span style={{ color: '#f59e0b', fontSize: '24px', fontWeight: 'bold' }}>✕</span>
                    </div>
                    <div>
                      <h3 style={{ color: 'white', fontWeight: '600', fontSize: '18px', marginBottom: '4px', marginTop: 0 }}>
                        Execution Failed
                      </h3>
                      <p style={{ color: 'rgb(212, 212, 212)', fontSize: '13px', lineHeight: '1.5', margin: 0 }}>
                        FFmpeg encountered an error
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => setExecutionError(null)}
                    style={{
                      background: 'transparent',
                      border: 'none',
                      color: 'rgb(163, 163, 163)',
                      cursor: 'pointer',
                      padding: '4px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      transition: 'color 0.2s',
                      flexShrink: 0
                    }}
                    onMouseEnter={(e) => e.target.style.color = 'white'}
                    onMouseLeave={(e) => e.target.style.color = 'rgb(163, 163, 163)'}
                  >
                    <FaTimes size={16} />
                  </button>
                </div>

                {/* Error Message */}
                <div style={{ padding: '16px 20px 20px 20px' }}>
                  <div style={{
                    background: 'rgba(245, 158, 11, 0.1)',
                    border: '1px solid rgba(245, 158, 11, 0.3)',
                    borderRadius: '8px',
                    padding: '12px',
                    fontFamily: 'monospace',
                    fontSize: '13px',
                    color: 'rgb(245, 158, 11)',
                    lineHeight: '1.5',
                    wordBreak: 'break-word',
                    maxHeight: '120px',
                    overflowY: 'auto'
                  }}>
                    {executionError}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Modals */}
        {showSettings && <SettingsModal onClose={() => setShowSettings(false)} />}
      </div>
    </div >
  );
};